version: "3.7"

services:
  db:
    image: mysql:5.7
    container_name: mysql
    restart: unless-stopped

    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

    volumes:
      - "./mysql:/var/lib/mysql"
      - "./config/php.ini:/usr/local/etc/php/conf.d/custom.ini"

  wordpress:
    image: wordpress:fpm
    container_name: wordpress
    restart: unless-stopped

    depends_on:
      - db

    links:
      - db

    volumes:
      - "./www:/var/www/html"
    
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress

  caddy:
    image: caddy
    restart: unless-stopped

    ports:
      - "80:80"
      - "443:443"

    links:
      - wordpress

    volumes_from:
      - wordpress

    volumes:
      - "./config/Caddyfile:/etc/caddy/Caddyfile"
      - "caddy_data:/data"
      - "caddy_config:/config"

volumes:
  caddy_data:
    external: true
  caddy_config:
